# Generated by Django 4.2.13 on 2024-07-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usermodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone_no',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
