# Generated by Django 4.2.13 on 2024-08-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usermodel_phone_no'),
        ('projects', '0002_projectmodel_tenand'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='users',
            field=models.ManyToManyField(null=True, to='users.usermodel'),
        ),
    ]
