# Generated by Django 4.2.13 on 2024-05-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_statusmodel_created_at_statusmodel_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='statusmodel',
            name='updated_at',
        ),
    ]
