# Generated by Django 4.2.13 on 2024-05-25 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0004_alter_statusmodel_status_name'),
        ('projects', '0002_projectmodel_tenand'),
        ('tenants', '0003_alter_tenantmodel_email_and_more'),
        ('users', '0002_alter_usermodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_table', to='projects.projectmodel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_table', to='status.statusmodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_table', to='tenants.tenantmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_table', to='users.usermodel')),
            ],
        ),
    ]
